import { COSMETICS, EARNABLE_COSMETICS, RARITY_LABEL } from '../lib/progress/catalog';
import { localDayKey, msUntilLocalMidnight, seasonInfo } from '../lib/progress/calendar';
import { buyShopOffer, claimSeason, dailyShop, emptyDay, getQuestProgress, levelProgress, nextAction, openCapsule, rerollQuest, SEASON_REWARDS, setDailyGoal } from '../lib/progress/core';
import { exportEnvelope, loadProgress, parseImport, PROGRESS_KEY, resetProgress, saveProgress } from '../lib/progress/storage';
import type { CosmeticType, ProgressStateV1, Reward } from '../lib/progress/types';

const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T|null;
const formatMinutes=(ms:number)=>`${Math.floor(ms/60_000)} min`;
const rewardLabel=(reward:Reward)=>reward.type==='credits'?`${reward.amount} krediittiä`:reward.type==='capsule'?`${reward.kind==='standard'?'Tavallinen':reward.kind==='golden'?'Kultainen':'Legendaarinen'} kapseli`:reward.type==='cosmetic'?COSMETICS.find(c=>c.id===reward.cosmeticId)?.name??'Kosmetiikka':reward.type==='rerollToken'?'Uudelleenarvontatunnus':'Putkisuoja';
let state=loadProgress();
function persist(next:ProgressStateV1){state=next;saveProgress(state);render();window.dispatchEvent(new CustomEvent('progress-updated'));}
function progressBar(value:number,max:number,label:string){const percent=Math.min(100,max?value/max*100:0);return `<div class="meter" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${percent}%"></span></div>`;}
function today(){const key=localDayKey();return state.daily[key]??emptyDay(state,key);}

function renderHome(){const panel=$('today-panel');if(!panel)return;const day=today(),action=nextAction(state),level=levelProgress(state.lifetime.xp),unopened=state.inventory.capsules.filter(c=>!c.openedAt).length;
  panel.innerHTML=`<a class="panel-link" href="/edistyminen/" aria-label="Avaa edistyminen"></a><h2>Tänään</h2><strong class="today-count">${day.uniqueItemIds.length} / ${state.settings.dailyGoal} tehtävää</strong>${progressBar(day.uniqueItemIds.length,state.settings.dailyGoal,'Päivätavoite')}<p>${formatMinutes(day.activeStudyMs)} · ${day.xp} XP</p><p>${state.streak.current} päivän putki · Taso ${level.level}</p>${unopened?`<p class="notice">${unopened} avaamatonta kapselia</p>`:''}<a class="button primary next-action" href="${action.href}">${action.label}</a>`;}
function renderProgress(){const root=$('progress-dashboard');if(!root)return;const day=today(),level=levelProgress(state.lifetime.xp);const lastDays=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(6-i));const key=localDayKey(date),value=state.daily[key]??emptyDay(state,key);return{key,value};});
  root.innerHTML=`
  <section class="dashboard-card"><h2>Tänään</h2><div class="stat-main">${day.uniqueItemIds.length} / ${state.settings.dailyGoal} tehtävää</div>${progressBar(day.uniqueItemIds.length,state.settings.dailyGoal,'Päivätavoite')}<div class="stat-grid"><span><strong>${formatMinutes(day.activeStudyMs)}</strong>Aktiivinen aika</span><span><strong>${day.xp}</strong>XP</span><span><strong>${day.completedItems}</strong>Suoritukset</span><span><strong>${day.modes.length}</strong>Harjoitustavat</span></div></section>
  <section class="dashboard-card"><h2>Päivätehtävät</h2><div class="quest-list">${day.quests.map(q=>`<article class="quest ${q.claimed?'done':''}"><div><strong>${q.label}</strong><span>${getQuestProgress(day,q)} / ${q.target}${q.kind==='active'?' ms':''} · ${q.xp} XP · ${q.credits} krediittiä</span></div>${progressBar(getQuestProgress(day,q),q.target,q.label)}${q.claimed?'<span class="status">Valmis</span>':`<button data-reroll="${q.slot}" class="compact">Arvo uudelleen</button>`}</article>`).join('')}</div><p>Kaikki kolme: kultainen palkintokapseli + 25 kausipistettä</p></section>
  <section class="dashboard-card"><h2>Putki ja viikko</h2><div class="stat-grid"><span><strong>${state.streak.current}</strong>Nykyinen putki</span><span><strong>${state.streak.longest}</strong>Pisin putki</span><span><strong>${state.inventory.streakFreezes} / 2</strong>Putkisuojaa</span><span><strong>${Object.entries(state.daily).filter(([key,d])=>key>=localDayKey(new Date(Date.now()-6*864e5))&&d.uniqueItemIds.length).length}</strong>Opiskelupäivää</span></div><h3>Viikkotehtävät</h3><ul class="clean-list"><li>Opiskele 5 eri päivänä</li><li>Harjoittele 100 eri kohdetta</li><li>Käytä kaikkia kolmea harjoitustapaa</li></ul></section>
  <section class="dashboard-card"><h2>Viimeiset seitsemän päivää</h2><div class="bar-chart" aria-hidden="true">${lastDays.map(({key,value})=>`<div><span style="height:${Math.min(100,value.uniqueItemIds.length*4)}%"></span><small>${key.slice(5)}</small></div>`).join('')}</div><table class="sr-table"><caption>Viimeisten seitsemän päivän suoritukset</caption><thead><tr><th>Päivä</th><th>Tehtäviä</th><th>Minuuttia</th><th>XP</th></tr></thead><tbody>${lastDays.map(({key,value})=>`<tr><th>${key}</th><td>${value.uniqueItemIds.length}</td><td>${Math.floor(value.activeStudyMs/60000)}</td><td>${value.xp}</td></tr>`).join('')}</tbody></table></section>
  <section class="dashboard-card"><h2>Koko aika</h2><p class="level-line">Taso ${level.level}<br><strong>${state.lifetime.xp} / ${level.nextThreshold} XP</strong></p><p class="muted">Taso kertoo harjoittelumäärästä, ei kielitaidon tasosta.</p><div class="stat-grid"><span><strong>${state.lifetime.completedItems}</strong>Suoritusta</span><span><strong>${formatMinutes(state.lifetime.activeStudyMs)}</strong>Aktiivista aikaa</span><span><strong>${state.lifetime.sessionsCompleted}</strong>Kierrosta</span><span><strong>${state.lifetime.studyDays}</strong>Opiskelupäivää</span><span><strong>${state.lifetime.retriesMastered}</strong>Hallittua kertausta</span></div></section>
  <section class="dashboard-card"><h2>Saavutukset</h2><div class="achievement-grid">${state.achievements.map(a=>`<article class="achievement ${a.unlockedAt?'unlocked':''}"><strong>${a.name}</strong><span>${a.description}</span><small>${a.unlockedAt?'Avattu':'Lukittu'}</small></article>`).join('')}</div></section>
  <section class="dashboard-card"><h2>Ennätykset</h2><dl class="record-list"><div><dt>Eniten tehtäviä päivässä</dt><dd>${state.records.mostItemsDay}</dd></div><div><dt>Eniten aktiivista aikaa päivässä</dt><dd>${formatMinutes(state.records.mostActiveMsDay)}</dd></div><div><dt>Eniten XP:tä päivässä</dt><dd>${state.records.mostXpDay}</dd></div><div><dt>Paras seitsemän päivän määrä</dt><dd>${state.records.bestSevenDayItems}</dd></div></dl></section>`;
  root.querySelectorAll<HTMLButtonElement>('[data-reroll]').forEach(button=>button.addEventListener('click',()=>{const next=rerollQuest(state,Number(button.dataset.reroll));if(next)persist(next);}));
}
function renderSettings(){const goal=$<HTMLSelectElement>('daily-goal');if(!goal)return;goal.value=String(state.settings.dailyGoal);const calm=$<HTMLInputElement>('calm-mode');if(calm)calm.checked=state.settings.calmMode;}
function renderRewards(){const root=$('rewards-dashboard');if(!root)return;const unopened=state.inventory.capsules.filter(c=>!c.openedAt);const filter=($<HTMLSelectElement>('collection-filter')?.value??'all');const collection=COSMETICS.filter(c=>!c.seasonExclusive&&(filter==='all'||c.type===filter));
  root.innerHTML=`<section class="dashboard-card inventory-head"><div><span>Krediitit</span><strong>${state.inventory.credits}</strong></div><div><span>Putkisuojat</span><strong>${state.inventory.streakFreezes} / 2</strong></div><div><span>Uudelleenarvonnat</span><strong>${state.inventory.rerollTokens}</strong></div></section>
  <section class="dashboard-card"><h2>Avaamattomat palkintokapselit</h2>${unopened.length?`<div class="capsule-list">${unopened.map(c=>`<button class="capsule" data-open="${c.id}">${c.kind==='standard'?'Tavallinen':c.kind==='golden'?'Kultainen':'Legendaarinen'} palkintokapseli <span>Avaa</span></button>`).join('')}</div>`:'<p>Ei avaamattomia kapseleita.</p>'}<details><summary>Mahdollisuudet ja suoja</summary><p>Tavallinen kapseli: Tavallinen 65 %, Harvinainen 25 %, Eeppinen 8 %, Legendaarinen 2 %. Kultainen takaa vähintään harvinaisen. Legendaarinen takaa legendaarisen.</p><p>Harvinainen tai parempi viimeistään ${4-state.loot.sinceRare} kapselin päästä · Eeppinen viimeistään ${12-state.loot.sinceEpic} kapselin päästä · Legendaarinen viimeistään ${40-state.loot.sinceLegendary} kapselin päästä.</p></details></section>
  <section class="dashboard-card"><h2>Varusteet</h2><div class="equipment">${(['theme','cardStyle','progressFrame','title'] as CosmeticType[]).map(type=>`<label>${type==='theme'?'Teema':type==='cardStyle'?'Korttityyli':type==='progressFrame'?'Edistyskehys':'Arvonimi'}<select data-equip="${type}">${COSMETICS.filter(c=>c.type===type&&state.inventory.ownedCosmeticIds.includes(c.id)).map(c=>`<option value="${c.id}" ${state.inventory.equipped[type]===c.id?'selected':''}>${c.name}</option>`).join('')}</select></label>`).join('')}</div></section>
  <section class="dashboard-card"><h2>Kokoelma <span>${state.inventory.ownedCosmeticIds.filter(id=>EARNABLE_COSMETICS.some(c=>c.id===id)).length} / ${EARNABLE_COSMETICS.length}</span></h2><div class="collection-grid">${collection.map(c=>{const owned=state.inventory.ownedCosmeticIds.includes(c.id);return`<article class="collectible rarity-${c.rarity} ${owned?'owned':'locked'}"><div class="cosmetic-swatch"></div><strong>${c.name}</strong><span>${RARITY_LABEL[c.rarity]}</span><small>${owned?c.description:'Lukittu'}</small></article>`}).join('')}</div></section>
  <section class="dashboard-card"><h2>Päivän kauppa</h2><div class="shop-grid">${dailyShop(state).map(o=>`<article class="offer"><strong>${o.label}</strong><span>${o.discounted?`<s>${o.originalPrice}</s> `:''}${o.price} krediittiä</span><button data-buy="${o.id}" ${o.purchased||state.inventory.credits<o.price?'disabled':''}>${o.purchased?'Lunastettu':'Lunasta'}</button></article>`).join('')}</div>${state.settings.calmMode?'':`<p class="muted">Valikoima vaihtuu ${new Date(msUntilLocalMidnight()).toISOString().slice(11,19)}</p>`}</section>`;
  root.querySelectorAll<HTMLButtonElement>('[data-open]').forEach(b=>b.addEventListener('click',()=>{const result=openCapsule(state,b.dataset.open!);if(result){persist(result.state);showCapsule(result.capsule);}}));
  root.querySelectorAll<HTMLButtonElement>('[data-buy]').forEach(b=>b.addEventListener('click',()=>{const next=buyShopOffer(state,b.dataset.buy!);if(next)persist(next);}));
  root.querySelectorAll<HTMLSelectElement>('[data-equip]').forEach(s=>s.addEventListener('change',()=>{const type=s.dataset.equip as CosmeticType,item=COSMETICS.find(c=>c.id===s.value&&c.type===type);if(item&&state.inventory.ownedCosmeticIds.includes(item.id)){const next=structuredClone(state);next.inventory.equipped[type]=item.id;persist(next);location.reload();}}));
}
function showCapsule(capsule:{rarity?:string;reward?:Reward}){const dialog=$<HTMLDialogElement>('capsule-dialog');if(!dialog||!capsule.reward)return;$('capsule-rarity')!.textContent=RARITY_LABEL[capsule.rarity as keyof typeof RARITY_LABEL];$('capsule-reward')!.textContent=rewardLabel(capsule.reward);dialog.showModal();}
function renderSeason(){const root=$('season-dashboard');if(!root)return;const info=seasonInfo(),tier=Math.min(30,Math.floor(state.seasons.points/100)),remainder=state.seasons.points%100;root.innerHTML=`<section class="dashboard-card season-head"><p>Kausi ${info.index+1}</p><h2>Kliininen kierto</h2><strong>Taso ${tier} · ${state.seasons.points} pistettä</strong>${progressBar(remainder,100,'Seuraava kausitaso')}<p>${Math.max(0,28-info.dayNumber)} päivää jäljellä</p></section><section class="dashboard-card"><h2>Kausipolku</h2><div class="season-path">${Array.from({length:30},(_,i)=>i+1).map(t=>{const unlocked=state.seasons.points>=t*100,claimed=state.seasons.claimedTiers.includes(t);return`<article class="tier ${unlocked?'unlocked':''}"><span>Taso ${t}</span><strong>${SEASON_REWARDS[t]!.map(rewardLabel).join(' + ')}</strong>${claimed?'<span>Lunastettu</span>':unlocked?`<button data-claim="${t}">Lunasta</button>`:'<span>Lukittu</span>'}</article>`}).join('')}</div></section><section class="dashboard-card"><h2>Henkilökohtainen viikkoliiga</h2><div class="league-name">${state.league.tier}</div><p>${state.league.weeklyXp} XP tällä viikolla</p><p>Ei vastustajia eikä keinotekoisia sijoituksia.</p>${state.league.previousResult?`<p>Edellinen tulos: ${state.league.previousResult}</p>`:''}</section>`;root.querySelectorAll<HTMLButtonElement>('[data-claim]').forEach(b=>b.addEventListener('click',()=>{const next=claimSeason(state,Number(b.dataset.claim));if(next)persist(next);}));}
function render(){state=loadProgress();renderHome();renderProgress();renderSettings();renderRewards();renderSeason();}

$<HTMLSelectElement>('daily-goal')?.addEventListener('change',event=>persist(setDailyGoal(state,Number((event.target as HTMLSelectElement).value) as 5|10|20|30)));
$<HTMLInputElement>('calm-mode')?.addEventListener('change',event=>{const next=structuredClone(state);next.settings.calmMode=(event.target as HTMLInputElement).checked;persist(next);document.documentElement.dataset.calm=String(next.settings.calmMode);});
$<HTMLSelectElement>('collection-filter')?.addEventListener('change',renderRewards);
$('export-progress')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(exportEnvelope(state),null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`medicinsk-svenska-progress-${localDayKey()}.json`;link.click();URL.revokeObjectURL(link.href);});
$<HTMLInputElement>('import-progress')?.addEventListener('change',async event=>{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const parsed=parseImport(await file.text()),status=$('data-status');if(!parsed.ok){if(status)status.textContent=parsed.error;return;}if(confirm('Korvataanko nykyinen edistyminen tuoduilla tiedoilla?')){persist(parsed.state);if(status)status.textContent='Tiedot tuotu.';}});
$('reset-progress')?.addEventListener('click',()=>{if(confirm('Nollataanko kaikki edistymis- ja palkintotiedot? Harjoitussessiot säilyvät.')){state=resetProgress();location.reload();}});
$<HTMLDialogElement>('capsule-dialog')?.addEventListener('click',event=>{if((event.target as HTMLElement).hasAttribute('data-close'))(event.currentTarget as HTMLDialogElement).close();});
window.addEventListener('storage',event=>{if(event.key===PROGRESS_KEY)render();});render();
