import { COSMETICS, EARNABLE_COSMETICS } from '../lib/progress/catalog';
import { localDayKey, msUntilLocalMidnight, seasonInfo } from '../lib/progress/calendar';
import { buyShopOffer, claimableSeasonCount, claimSeason, dailyShop, emptyDay, getQuestProgress, levelProgress, openCapsule, rerollQuest, SEASON_REWARDS, setDailyGoal } from '../lib/progress/core';
import { achievementCopy, boxCopy, leagueCopy, leagueResultCopy, plural, questCopy, rarityCopy, rewardCopy, weeklyQuestCopy } from '../lib/progress/copy';
import { resolveDailyQuestAction, type ResumableSession } from '../lib/progress/daily-quest-action';
import { exportEnvelope, loadProgress, parseImport, PROGRESS_KEY, resetProgress, saveProgress } from '../lib/progress/storage';
import { dismissDailyOverlay, loadUiPreferences, shouldAutoOpenDailyOverlay } from '../lib/progress/ui-preferences';
import type { CosmeticType, ExerciseMode, ProgressStateV1, Quest, Reward } from '../lib/progress/types';
import { buildSessionUrl } from '../lib/session-url';
import { isSessionComplete, isStoredSession, type CreateSessionOptions, type FlashcardSession } from '../lib/session';
import { buildPhraseSessionUrl } from '../lib/phrase-url';
import { isPhraseSessionComplete, isStoredPhraseSession, type PhraseSession, type PhraseSessionConfiguration } from '../lib/phrase-session';
import { buildDescriptionSessionUrl } from '../lib/description-url';
import { isStoredDescriptionSession, type DescriptionSession, type DescriptionSessionConfiguration } from '../lib/description-session';

const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T|null;
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const formatMinutes=(ms:number)=>`${Math.floor(ms/60_000)} min`;
const typeCopy:Record<CosmeticType,string>={theme:'Tema',cardStyle:'Kortstil',progressFrame:'Framstegsram',title:'Titel'};
let state=loadProgress();
let collectionFilter='all';
let autoOpenChecked=false;
const SESSION_KEYS:Record<ExerciseMode,string>={flashcards:'medicinsk-svenska.flashcard-session.v1',phrases:'medicinsk-svenska.phrase-session.v1',descriptions:'medicinsk-svenska.description-session.v1'};

interface DailySessionCatalog {
  cards: [string,string][]; decks:string[];
  phrases:[string,string][]; phraseCategories:string[];
  descriptions:[string,string][]; descriptionCategories:string[];
}

function dailySessionCatalog():DailySessionCatalog|null{const node=$<HTMLScriptElement>('daily-session-catalog');if(!node)return null;try{return JSON.parse(node.textContent??'null') as DailySessionCatalog;}catch{return null;}}
function storedValue(key:string):unknown{try{return JSON.parse(localStorage.getItem(key)??'null');}catch{return null;}}
function resumableSessions():Partial<Record<ExerciseMode,ResumableSession>>{const catalog=dailySessionCatalog();if(!catalog)return{};const sessions:Partial<Record<ExerciseMode,ResumableSession>>={};
  const flash=storedValue(SESSION_KEYS.flashcards);if(flash&&typeof flash==='object'){const candidate=flash as FlashcardSession,expected:CreateSessionOptions={sessionId:candidate.sessionId,mode:candidate.mode,direction:candidate.direction,requestedAmount:candidate.requestedAmount,...(candidate.mode==='deck'&&candidate.sourceDeckId?{sourceDeckId:candidate.sourceDeckId}:{})};if(isStoredSession(flash,{cardDeckById:new Map(catalog.cards),validDeckIds:new Set(catalog.decks),expected})&&!isSessionComplete(candidate))sessions.flashcards={href:buildSessionUrl(expected),startedAt:candidate.startedAt};}
  const phrase=storedValue(SESSION_KEYS.phrases);if(phrase&&typeof phrase==='object'){const candidate=phrase as PhraseSession,expected:PhraseSessionConfiguration={sessionId:candidate.sessionId,mode:candidate.mode,requestedAmount:candidate.requestedAmount,...(candidate.mode==='category'&&candidate.sourceCategoryId?{sourceCategoryId:candidate.sourceCategoryId}:{})};if(isStoredPhraseSession(phrase,{categoryByPhraseId:new Map(catalog.phrases),validCategoryIds:new Set(catalog.phraseCategories),expected})&&!isPhraseSessionComplete(candidate))sessions.phrases={href:buildPhraseSessionUrl(expected),startedAt:candidate.startedAt};}
  const description=storedValue(SESSION_KEYS.descriptions);if(description&&typeof description==='object'){const candidate=description as DescriptionSession,expected:DescriptionSessionConfiguration={sessionId:candidate.sessionId,sourceMode:candidate.sourceMode,requestedAmount:candidate.requestedAmount,roundType:candidate.roundType,...(candidate.sourceMode==='category'&&candidate.sourceCategoryId?{sourceCategoryId:candidate.sourceCategoryId}:{})};if(isStoredDescriptionSession(description,{categoryByExerciseId:new Map(catalog.descriptions),validCategoryIds:new Set(catalog.descriptionCategories),expected})&&candidate.currentIndex<candidate.selectedExerciseIds.length)sessions.descriptions={href:buildDescriptionSessionUrl(expected),startedAt:candidate.startedAt};}
  return sessions;
}
function freshSessionUrls():Record<ExerciseMode,string>{return{flashcards:buildSessionUrl({sessionId:crypto.randomUUID(),mode:'lucky',direction:'fi-sv',requestedAmount:10}),phrases:buildPhraseSessionUrl({sessionId:crypto.randomUUID(),mode:'all',requestedAmount:10}),descriptions:buildDescriptionSessionUrl({sessionId:crypto.randomUUID(),sourceMode:'all',requestedAmount:10,roundType:'initial'})};}
function persist(next:ProgressStateV1){state=next;saveProgress(state);render();window.dispatchEvent(new CustomEvent('progress-updated'));}
function progressBar(value:number,max:number,label:string){const percent=Math.min(100,max?value/max*100:0);return `<div class="meter" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${percent}%"></span></div>`;}
function today(){const key=localDayKey();return state.daily[key]??emptyDay(state,key);}
function questValue(quest:Quest,value:number){return quest.kind==='active'?`${Math.floor(value/60_000)} / 5 min`:`${value} / ${quest.target}`;}
function questRows(day= today(),allowReroll=true){return day.quests.map(quest=>{const copy=questCopy(quest),value=getQuestProgress(day,quest),canReroll=allowReroll&&!quest.claimed&&(quest.slot!==1||!day.freeRerollUsed||state.inventory.rerollTokens>0);return `<article class="quest ${quest.claimed?'done':''}" data-quest-slot="${quest.slot}"><div class="quest-head"><div><strong lang="sv">${copy.sv}</strong><small lang="fi">${copy.fi}</small></div><span class="quest-progress" lang="sv">${quest.claimed?'Klart':questValue(quest,value)}</span></div>${progressBar(value,quest.target,`${copy.sv}: ${questValue(quest,value)}`)}<div class="quest-meta" lang="sv"><span>+${quest.xp} XP · +${quest.credits} krediter · +${quest.seasonPoints} säsongspoäng</span>${canReroll?`<button data-reroll="${quest.slot}" class="compact">Byt uppdrag</button>`:''}</div></article>`;}).join('');}
function bindRerolls(root:HTMLElement){root.querySelectorAll<HTMLButtonElement>('[data-reroll]').forEach(button=>button.addEventListener('click',()=>{const next=rerollQuest(state,Number(button.dataset.reroll));if(next)persist(next);}));}

function overlayQuestRows(day= today()){return day.quests.map(quest=>{const copy=questCopy(quest),value=getQuestProgress(day,quest),valueCopy=questValue(quest,value),canReroll=!quest.claimed&&(quest.slot!==1||!day.freeRerollUsed||state.inventory.rerollTokens>0),body=`<span class="daily-quest-head"><span><strong lang="sv">${copy.sv}</strong><small lang="fi">${copy.fi}</small></span><b lang="sv">${quest.claimed?'Klart':valueCopy}</b></span>${progressBar(value,quest.target,`${copy.sv}: ${valueCopy}`)}<span class="daily-quest-reward" lang="sv">+${quest.xp} XP · +${quest.credits} krediter · +${quest.seasonPoints} säsongspoäng</span>`;return `<article class="daily-quest-row ${quest.claimed?'done':''}" data-quest-slot="${quest.slot}">${quest.claimed?`<div class="daily-quest-complete">${body}</div>`:`<button type="button" class="daily-quest-action" data-quest-action="${quest.slot}" data-focus-id="quest-${quest.slot}">${body}<span class="daily-quest-start" lang="sv">Starta</span></button>`}${canReroll?`<button type="button" data-reroll="${quest.slot}" data-focus-id="reroll-${quest.slot}" class="compact daily-reroll" lang="sv">Byt uppdrag</button>`:''}</article>`;}).join('');}
function bindHomeActions(root:HTMLElement,day= today()){bindRerolls(root);root.querySelectorAll<HTMLButtonElement>('[data-quest-action]').forEach(button=>button.addEventListener('click',()=>{const quest=day.quests.find(item=>item.slot===Number(button.dataset.questAction));if(!quest)return;const action=resolveDailyQuestAction(quest,{...(state.lastUsedMode?{lastUsedMode:state.lastUsedMode}:{}),modesUsedToday:day.modes,sessions:resumableSessions(),freshUrls:freshSessionUrls()});if(!action)return;if(!action.resumesSession)localStorage.removeItem(SESSION_KEYS[action.mode]);location.assign(action.href);}));}
function openDailyOverlay(){const dialog=$<HTMLDialogElement>('daily-overlay');if(!dialog||dialog.open||document.querySelector('dialog[open]'))return;dialog.showModal();const target=dialog.querySelector<HTMLElement>('[data-quest-action]')??$('daily-overlay-title');target?.focus({preventScroll:true});}
function renderHome(){const launcher=$<HTMLButtonElement>('daily-launcher'),root=$('daily-overlay-content');if(!launcher||!root)return;const day=today(),goalComplete=day.uniqueItemIds.length>=state.settings.dailyGoal,questCount=day.quests.filter(quest=>quest.claimed).length,allComplete=questCount===day.quests.length,activeFocus=(document.activeElement as HTMLElement|null)?.dataset.focusId;
  $('daily-launcher-quests')!.textContent=`Dagens uppdrag ${questCount} / ${day.quests.length}`;$('daily-launcher-goal')!.textContent=goalComplete?'Dagens mål klart':`Dagens mål ${day.uniqueItemIds.length} / ${state.settings.dailyGoal}`;
  root.innerHTML=`<section class="overlay-goal"><div><h3 lang="sv">Dagens mål</h3><strong lang="sv">${goalComplete?'Klart':`${day.uniqueItemIds.length} / ${state.settings.dailyGoal}`}</strong></div>${progressBar(day.uniqueItemIds.length,state.settings.dailyGoal,'Dagens mål')}<small lang="sv">Vanlig låda · 10 krediter · 20 säsongspoäng</small></section><div class="daily-overlay-quests">${overlayQuestRows(day)}</div><footer class="daily-all-bonus"><strong lang="sv">${allComplete?'Alla tre uppdrag klara':'Slutför alla tre och få en gyllene låda'}</strong><small lang="fi">Suorita kaikki kolme ja saat kultaisen yllätyslaatikon.</small></footer>`;
  bindHomeActions(root,day);if(activeFocus&&$('daily-overlay')?.hasAttribute('open'))(root.querySelector<HTMLElement>(`[data-focus-id="${activeFocus}"]`)??root.querySelector<HTMLElement>('[data-quest-action]')??$<HTMLButtonElement>('daily-overlay-close'))?.focus({preventScroll:true});
}

function renderProgress(){const root=$('progress-dashboard');if(!root)return;const day=today(),level=levelProgress(state.lifetime.xp),lastDays=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(6-i));const key=localDayKey(date);return{key,value:state.daily[key]??emptyDay(state,key)};}),claimable=claimableSeasonCount(state);
  root.innerHTML=`<section class="dashboard-card" lang="sv"><h2>I dag</h2><div class="stat-main">${day.uniqueItemIds.length} / ${state.settings.dailyGoal}</div>${progressBar(day.uniqueItemIds.length,state.settings.dailyGoal,'Dagens mål')}<div class="stat-grid"><span><strong>${formatMinutes(day.activeStudyMs)}</strong>Aktiv tid</span><span><strong>${day.xp}</strong>XP</span><span><strong>${day.completedItems}</strong>Uppgifter</span><span><strong>${day.modes.length}</strong>Övningstyper</span></div>${claimable?`<a class="reward-alert" href="/kausi/#reward-track">${claimable} säsongsbelöning väntar</a>`:''}</section>
  <section class="dashboard-card"><h2 lang="sv">Dagens uppdrag</h2><div class="quest-list">${questRows(day)}</div><div class="all-quests-bonus"><strong lang="sv">Slutför alla tre och få en gyllene låda</strong><small lang="fi">Suorita kaikki kolme ja saat kultaisen yllätyslaatikon.</small></div></section>
  <section class="dashboard-card" lang="sv"><h2>Svit och vecka</h2><div class="stat-grid"><span><strong>${state.streak.current}</strong>Nuvarande svit</span><span><strong>${state.streak.longest}</strong>Längsta svit</span><span><strong>${state.inventory.streakFreezes} / 2</strong>Svitfrysningar</span><span><strong>${Object.values(state.daily).filter(value=>value.uniqueItemIds.length).length}</strong>Studiedagar</span></div><h3>Veckans uppdrag</h3><ul class="clean-list">${weeklyQuestCopy.map(copy=>`<li><span lang="sv">${copy.sv}</span><small lang="fi">${copy.fi}</small></li>`).join('')}</ul></section>
  <section class="dashboard-card" lang="sv"><h2>De senaste sju dagarna</h2><div class="bar-chart" aria-hidden="true">${lastDays.map(({key,value})=>`<div><span style="height:${Math.min(100,value.uniqueItemIds.length*4)}%"></span><small>${key.slice(5)}</small></div>`).join('')}</div><table class="sr-table"><caption>Uppgifter under de senaste sju dagarna</caption><thead><tr><th>Dag</th><th>Uppgifter</th><th>Minuter</th><th>XP</th></tr></thead><tbody>${lastDays.map(({key,value})=>`<tr><th>${key}</th><td>${value.uniqueItemIds.length}</td><td>${Math.floor(value.activeStudyMs/60000)}</td><td>${value.xp}</td></tr>`).join('')}</tbody></table></section>
  <section class="dashboard-card" lang="sv"><h2>Totalt</h2><p class="level-line">Nivå ${level.level}<br><strong>${state.lifetime.xp} / ${level.nextThreshold} <abbr title="erfarenhetspoäng">XP</abbr></strong></p><p>Erfarenhetspoäng (XP): ${state.lifetime.xp}</p><p class="muted">Nivån visar hur mycket du har övat, inte din språknivå.</p><div class="stat-grid"><span><strong>${state.lifetime.completedItems}</strong>Uppgifter</span><span><strong>${formatMinutes(state.lifetime.activeStudyMs)}</strong>Aktiv tid</span><span><strong>${state.lifetime.sessionsCompleted}</strong>Övningspass</span><span><strong>${state.lifetime.studyDays}</strong>Studiedagar</span><span><strong>${state.lifetime.retriesMastered}</strong>Bemästrade repetitioner</span></div></section>
  <section class="dashboard-card" lang="sv"><h2>Prestationer</h2><div class="achievement-grid">${state.achievements.map(item=>{const copy=achievementCopy(item);return`<article class="achievement ${item.unlockedAt?'unlocked':''}"><strong>${copy.name}</strong><span>${copy.description}</span><small>${item.unlockedAt?'Upplåst':'Låst'}</small></article>`}).join('')}</div></section>
  <section class="dashboard-card" lang="sv"><h2>Personliga rekord</h2><dl class="record-list"><div><dt>Flest uppgifter på en dag</dt><dd>${state.records.mostItemsDay}</dd></div><div><dt>Mest aktiv tid på en dag</dt><dd>${formatMinutes(state.records.mostActiveMsDay)}</dd></div><div><dt>Mest XP på en dag</dt><dd>${state.records.mostXpDay}</dd></div><div><dt>Bästa sju dagar</dt><dd>${state.records.bestSevenDayItems}</dd></div></dl></section>`;
  bindRerolls(root);
}
function renderSettings(){const goal=$<HTMLSelectElement>('daily-goal');if(!goal)return;goal.value=String(state.settings.dailyGoal);const calm=$<HTMLInputElement>('calm-mode');if(calm)calm.checked=state.settings.calmMode;}
function shopLabel(type:string,itemId:string){if(type==='cosmetic')return COSMETICS.find(item=>item.id===itemId)?.name??'Kosmetik';if(type==='utility')return itemId==='streakFreeze'?'Svitfrysning':'Uppdragsbyte';return boxCopy[itemId as keyof typeof boxCopy];}
function renderRewards(){const root=$('rewards-dashboard');if(!root)return;const unopened=state.inventory.capsules.filter(item=>!item.openedAt),collection=COSMETICS.filter(item=>!item.seasonExclusive&&(collectionFilter==='all'||item.type===collectionFilter));
  root.innerHTML=`<section id="unopened-boxes" class="dashboard-card full-width" lang="sv"><h2>Överraskningslådor</h2><h3>Oöppnade lådor</h3>${unopened.length?`<div class="capsule-list">${unopened.map(item=>`<button class="capsule" data-open="${item.id}">${boxCopy[item.kind]} <span>Öppna</span></button>`).join('')}</div>`:'<p>Inga oöppnade lådor.</p>'}<details><summary>Chanser och garanti</summary><p>Vanlig 65 % · Sällsynt 25 % · Episk 8 % · Legendarisk 2 %</p><p>Sällsynt eller bättre senast om ${plural(4-state.loot.sinceRare,'låda','lådor')}<br>Episk eller bättre senast om ${plural(12-state.loot.sinceEpic,'låda','lådor')}<br>Legendarisk senast om ${plural(40-state.loot.sinceLegendary,'låda','lådor')}</p></details></section>
  <section class="dashboard-card inventory-head" lang="sv"><div><span>Krediter</span><strong>${state.inventory.credits}</strong></div><div><span>Svitfrysningar</span><strong>${state.inventory.streakFreezes} / 2</strong></div><div><span>Uppdragsbyten</span><strong>${state.inventory.rerollTokens}</strong></div></section>
  <section class="dashboard-card" lang="sv"><h2>Utrustning</h2><div class="equipment">${(['theme','cardStyle','progressFrame','title'] as CosmeticType[]).map(type=>`<label>${typeCopy[type]}<select data-equip="${type}">${COSMETICS.filter(item=>item.type===type&&state.inventory.ownedCosmeticIds.includes(item.id)).map(item=>`<option value="${item.id}" ${state.inventory.equipped[type]===item.id?'selected':''}>${item.name}</option>`).join('')}</select></label>`).join('')}</div></section>
  <section class="dashboard-card" lang="sv"><h2>Samling <span>${state.inventory.ownedCosmeticIds.filter(id=>EARNABLE_COSMETICS.some(item=>item.id===id)).length} / ${EARNABLE_COSMETICS.length}</span></h2><label class="filter-label">Visa i samlingen<select id="collection-filter"><option value="all" ${collectionFilter==='all'?'selected':''}>Alla</option><option value="theme" ${collectionFilter==='theme'?'selected':''}>Teman</option><option value="cardStyle" ${collectionFilter==='cardStyle'?'selected':''}>Kortstilar</option><option value="progressFrame" ${collectionFilter==='progressFrame'?'selected':''}>Framstegsramar</option><option value="title" ${collectionFilter==='title'?'selected':''}>Titlar</option></select></label><div class="collection-grid">${collection.map(item=>{const owned=state.inventory.ownedCosmeticIds.includes(item.id);return`<article class="collectible rarity-${item.rarity} ${owned?'owned':'locked'}"><div class="cosmetic-swatch"></div><strong>${item.name}</strong><span>${rarityCopy[item.rarity]}</span><small>${owned?item.description:'Låst'}</small>${owned&&state.inventory.equipped[item.type]!==item.id?`<button data-use="${item.id}" class="compact">Använd</button>`:owned?'<b>Utrustad</b>':''}</article>`}).join('')}</div></section>
  <section class="dashboard-card full-width" lang="sv"><h2>Dagens butik</h2><div class="shop-grid">${dailyShop(state).map(offer=>`<article class="offer"><strong>${shopLabel(offer.type,offer.itemId)}</strong><span>${offer.discounted?`<s>${offer.originalPrice}</s> `:''}${offer.price} krediter</span><button data-buy="${offer.id}" ${offer.purchased||state.inventory.credits<offer.price?'disabled':''}>${offer.purchased?'Redan hämtad':`Hämta för ${offer.price} krediter`}</button></article>`).join('')}</div>${state.settings.calmMode?'':`<p class="muted">Nya erbjudanden om ${new Date(msUntilLocalMidnight()).toISOString().slice(11,19)}</p>`}</section>`;
  root.querySelectorAll<HTMLButtonElement>('[data-open]').forEach(button=>button.addEventListener('click',()=>{const result=openCapsule(state,button.dataset.open!);if(result){persist(result.state);showCapsule(result.capsule);}}));root.querySelectorAll<HTMLButtonElement>('[data-buy]').forEach(button=>button.addEventListener('click',()=>{const next=buyShopOffer(state,button.dataset.buy!);if(next)persist(next);}));
  root.querySelectorAll<HTMLButtonElement>('[data-use]').forEach(button=>button.addEventListener('click',()=>{const item=COSMETICS.find(value=>value.id===button.dataset.use);if(item){const next=structuredClone(state);next.inventory.equipped[item.type]=item.id;persist(next);}}));
  root.querySelectorAll<HTMLSelectElement>('[data-equip]').forEach(select=>select.addEventListener('change',()=>{const type=select.dataset.equip as CosmeticType,item=COSMETICS.find(value=>value.id===select.value&&value.type===type);if(item&&state.inventory.ownedCosmeticIds.includes(item.id)){const next=structuredClone(state);next.inventory.equipped[type]=item.id;persist(next);}}));
  $<HTMLSelectElement>('collection-filter')?.addEventListener('change',event=>{collectionFilter=(event.target as HTMLSelectElement).value;renderRewards();});
}
function showCapsule(capsule:{rarity?:string;reward?:Reward}){const dialog=$<HTMLDialogElement>('capsule-dialog');if(!dialog||!capsule.reward)return;$('capsule-rarity')!.textContent=rarityCopy[capsule.rarity as keyof typeof rarityCopy];$('capsule-reward')!.textContent=rewardCopy(capsule.reward);dialog.showModal();}
function renderSeason(){const root=$('season-dashboard');if(!root)return;const info=seasonInfo(),step=Math.min(30,Math.floor(state.seasons.points/100)),remainder=state.seasons.points%100,claimable=claimableSeasonCount(state);
  root.innerHTML=`<section class="dashboard-card season-head" lang="sv"><p>Säsong ${info.index+1}</p><h2>Klinisk rotation</h2><strong>Steg ${step} av 30</strong><p>Säsongspoäng: ${state.seasons.points}</p>${progressBar(remainder,100,'Till nästa steg')}<p>${Math.max(0,28-info.dayNumber)} dagar kvar</p></section><section id="reward-track" class="dashboard-card" lang="sv"><div class="section-title"><h2>Belöningsspår</h2>${claimable?`<button data-claim-all>Hämta alla</button>`:''}</div><div class="season-path">${Array.from({length:30},(_,index)=>index+1).map(tier=>{const unlocked=state.seasons.points>=tier*100,claimed=state.seasons.claimedTiers.includes(tier);return`<article class="tier ${unlocked?'unlocked':''}"><span>Steg ${tier}</span><strong>${SEASON_REWARDS[tier]!.map(rewardCopy).join(' + ')}</strong>${claimed?'<span>Hämtad</span>':unlocked?`<button data-claim="${tier}">Hämta</button>`:'<span>Låst</span>'}</article>`}).join('')}</div></section><section id="league" class="dashboard-card" lang="sv"><h2>Veckoliga</h2><div class="league-name">${leagueCopy[state.league.tier]}</div><p>Veckans XP: ${state.league.weeklyXp}</p><p>Till nästa liga</p><p>Ingen påhittad topplista och inga falska motståndare.</p>${state.league.result?`<p>${leagueResultCopy(state.league.result)}</p>`:''}</section>`;
  root.querySelectorAll<HTMLButtonElement>('[data-claim]').forEach(button=>button.addEventListener('click',()=>{const next=claimSeason(state,Number(button.dataset.claim));if(next)persist(next);}));root.querySelector<HTMLButtonElement>('[data-claim-all]')?.addEventListener('click',()=>{let next=state;for(let tier=1;tier<=30;tier++)next=claimSeason(next,tier)??next;if(next!==state)persist(next);});
}
function render(){state=loadProgress();renderHome();renderProgress();renderSettings();renderRewards();renderSeason();}

function checkDailyAutoOpen(){if(autoOpenChecked||!$('daily-launcher'))return;autoOpenChecked=true;queueMicrotask(()=>{const dialog=$<HTMLDialogElement>('daily-overlay'),day=today();if(!dialog)return;const otherModalOpen=[...document.querySelectorAll<HTMLDialogElement>('dialog[open]')].some(item=>item!==dialog);if(shouldAutoOpenDailyOverlay({pathname:location.pathname,localDay:localDayKey(),preferences:loadUiPreferences(),calmMode:state.settings.calmMode,dailyGoalComplete:day.uniqueItemIds.length>=state.settings.dailyGoal,dailyQuestsComplete:day.quests.every(quest=>quest.claimed),otherModalOpen}))openDailyOverlay();});}

$<HTMLSelectElement>('daily-goal')?.addEventListener('change',event=>persist(setDailyGoal(state,Number((event.target as HTMLSelectElement).value) as 5|10|20|30)));
$<HTMLInputElement>('calm-mode')?.addEventListener('change',event=>{const next=structuredClone(state);next.settings.calmMode=(event.target as HTMLInputElement).checked;persist(next);document.documentElement.dataset.calm=String(next.settings.calmMode);});
$('export-progress')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(exportEnvelope(state),null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`medicinsk-svenska-progress-${localDayKey()}.json`;link.click();URL.revokeObjectURL(link.href);});
$<HTMLInputElement>('import-progress')?.addEventListener('change',async event=>{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const parsed=parseImport(await file.text()),status=$('data-status');if(!parsed.ok){if(status)status.textContent=parsed.error;return;}if(confirm('Korvataanko nykyinen edistyminen tuoduilla tiedoilla?')){persist(parsed.state);if(status)status.textContent='Tiedot tuotu.';}});
$('reset-progress')?.addEventListener('click',()=>{if(confirm('Nollataanko kaikki edistymis- ja palkintotiedot? Harjoitussessiot säilyvät.')){state=resetProgress();location.reload();}});
$<HTMLDialogElement>('capsule-dialog')?.addEventListener('click',event=>{if((event.target as HTMLElement).hasAttribute('data-close'))(event.currentTarget as HTMLDialogElement).close();});
$<HTMLButtonElement>('daily-launcher')?.addEventListener('click',openDailyOverlay);
$<HTMLButtonElement>('daily-overlay-close')?.addEventListener('click',()=> $<HTMLDialogElement>('daily-overlay')?.close());
$<HTMLDialogElement>('daily-overlay')?.addEventListener('click',event=>{if(event.target===event.currentTarget)(event.currentTarget as HTMLDialogElement).close();});
$<HTMLDialogElement>('daily-overlay')?.addEventListener('close',()=>{try{dismissDailyOverlay();}catch{}$<HTMLButtonElement>('daily-launcher')?.focus({preventScroll:true});});
window.addEventListener('progress-updated',render);
window.addEventListener('storage',event=>{if(event.key===PROGRESS_KEY)render();});render();checkDailyAutoOpen();
